### ISSUE TITLE
About how to add rep

### ISSUE THREAD

**Issue by Koukotsukan** [yyLeaves/DS-Project#7]
Hi, I cannot understand how you implement the addition of reputation, so may I ask if you could write comments or description on how to do it? Thanks.

**Comment by yyLeaves** [comment]
https://github.com/yyLeaves/DS-Project/commit/9a8138886be45604efbff59d98085e0de21984f5
Please tell me if it works
@Koukotsukan

**Comment by Koukotsukan** [comment]
> [b951e04](https://github.com/yyLeaves/DS-Project/commit/b951e04fe2e0e1342619b471d64bdad1ca183b55)
> Please tell me if it works

It works

**Comment by Koukotsukan** [comment]
Noted with thanks
